# Generated by Django 2.0.4 on 2019-02-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingcode',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workingcode',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
