# Generated by Django 2.0.4 on 2019-02-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20190205_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='working',
            options={'permissions': (('post_working', 'Can add working schedule'), ('approve_working', 'Can approve working schedule'), ('accept_working', 'Can accept working schedule'))},
        ),
    ]
