# Generated by Django 2.0.4 on 2019-02-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20190205_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='working',
            options={'permissions': (('request_working', 'Can request working schedule'), ('approve_working', 'Can approve working schedule'), ('accept_working', 'Can accept/reject working schedule'))},
        ),
    ]
