# Generated by Django 2.1.5 on 2019-02-06 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20190205_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='working',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='working',
            name='accepted_result',
            field=models.CharField(choices=[('NA', 'Not Defined yet'), ('ACCEPT', 'Accepted'), ('REJECT', 'Rejected')], default='NA', max_length=10),
        ),
        migrations.AddField(
            model_name='working',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='working',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='working',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='working',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='working',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='working',
            name='status',
            field=models.CharField(choices=[('WORKING', 'On Working'), ('FINISH', 'Finished'), ('PRE_APPROVE', 'Pre-approved'), ('APPROVE', 'Approve'), ('ACCEPT', 'Accepted'), ('REJECT', 'Rejected'), ('COMPLETE', 'Completed')], default='WORKING', max_length=10),
        ),
    ]
