# Generated by Django 2.1.5 on 2019-02-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20190206_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='working',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='working',
            name='start_time',
        ),
    ]
