# Generated by Django 2.1.5 on 2019-03-06 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_date', models.DateField()),
                ('stamp_time', models.TimeField()),
                ('stamp_status', models.CharField(blank=True, max_length=5, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'permissions': (('process_attendance_file', 'Can process attendances file'),),
            },
        ),
        migrations.CreateModel(
            name='AttendanceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('filename', models.FileField(blank=True, null=True, upload_to='logs/attendances/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('uploaded_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'permissions': (('import_attendance_file', 'Can import attendances file'),),
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendancefile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.AttendanceFile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
    ]
