# Generated by Django 2.1.5 on 2019-02-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='log_status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
