# Generated by Django 2.1.5 on 2019-02-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancefile',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancefile',
            name='uploaded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
