# Generated by Django 2.1.5 on 2019-02-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20190228_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancefile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
