# Generated by Django 2.1.5 on 2019-03-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancefile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='working',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='attendancefile',
            name='filename',
            field=models.FileField(blank=True, null=True, upload_to='logs/attendances/%Y/%m/%d/'),
        ),
    ]
