# Generated by Django 2.1.5 on 2019-03-03 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20190303_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendancefile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.AttendanceFile'),
            preserve_default=False,
        ),
    ]
