# Generated by Django 2.1.5 on 2019-03-04 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_attendancefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='log_date',
            new_name='stamp_date',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='log_status',
            new_name='stamp_status',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='log_time',
            new_name='stamp_time',
        ),
    ]
