# Generated by Django 2.1.5 on 2019-03-04 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20190304_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'permissions': (('process_attendance_file', 'Can process attendances file'),)},
        ),
        migrations.AlterModelOptions(
            name='attendancefile',
            options={'permissions': (('import_attendance_file', 'Can import attendances file'),)},
        ),
    ]
